Review Metrics
GTech1256/go-yandex-metrics-tpl pull request #7
Opened 2023-10-10 14:37 UTC by GTech1256

2023-10-11 07:38 UTC, edylcrm requested changes

2023-10-11 07:38 UTC, edylcrm commented on cmd/agent/main.go
>  package main
Комментарии разделены на несколько типов:
**[BLOCKER]** - Проблема, не решив которую принять работу нельзя
**[LINT]** - Заменичение, опционально к выполнению.
**[FYI]** - просто ремарка

2023-10-11 07:38 UTC, edylcrm commented on cmd/agent/main.go
> +	shutdown := make(chan int)
**[FYI]** Хорошей практикой считается отслеживание сигналов ОС, чтобы можно было корректно завершить выполнение программы. Для этого используется функционал: https://gobyexample.com/signals

2023-10-11 07:38 UTC, edylcrm commented on cmd/server/main.go
> +	_, err := server.New(cfg, logger)
**[FYI]** Здесь так же было бы хорошо слушать сигналы ОС и корректно завершать http сервис чтобы пользователи в момент редеплоя приложения или принудительного завершения получили ответ.
Пример работы с сигналами: https://gobyexample.com/signals
Как корректно завершать http сервис: https://pkg.go.dev/net/http#Server.SetKeepAlivesEnabled и https://pkg.go.dev/net/http#Server.Shutdown

2023-10-11 07:38 UTC, edylcrm commented on internal/server/app.go
> +type App interface {
**[LINT]** Здесь можно обойтись и без интерфейса

2023-10-11 07:38 UTC, edylcrm commented on internal/agent/service/server/service.go
> +	Service interface {
**[FYI]** В golang есть два подхода расположения интерфейсом. Первый классический который используется во многих языках программирования (Java, Php, C# etc.) и второй когда интерфейс расположен по месту использования т.е. в этом случае этот интерфейс лежит в handler. В golang очень круто реализована работа с интерфейсами за счет duck typing. Подробней рассказывают тут: https://www.youtube.com/watch?v=eYHCCht8eX4
Лично мне второй способ нравится намного больше и везде где я работал принят именно он.

2023-10-11 07:38 UTC, edylcrm commented on internal/agent/service/server/service/start_report.go
> +	go func() {
**[BLOCKER]** Здесь точно нужна отдельная горутина чтобы читать из канала? Может сделать как-то попроще? Почему сразу из репозитория прочитать нельзя?

2023-10-11 07:38 UTC, edylcrm commented on internal/domain/entity/MetricCounter.go
> +package entity
**[BLOCKER]** Все таки выглядит немного странно, agent и server два разных приложения, но используют общий DTO, я бы все так не делал

2023-10-11 07:38 UTC, edylcrm commented on internal/server/repository/metric/storage.go
> +	return value, ok
**[BLOCKER]** Давай заменим bool на error, в дальнейшем будут добавляться другие виды хранилища
```
 GetGaugeValue(name string) (entity.GaugeValue, error)
 ```

2023-10-11 07:38 UTC, edylcrm commented on internal/server/repository/metric/storage.go
> +func (s *storage) GetCounterValue(name string) (entity.CounterValue, bool) {
**[BLOCKER]** Здесь тоже

2023-10-13 00:04 UTC, GTech1256 commented on internal/server/repository/metric/storage.go
> +func (s *storage) GetCounterValue(name string) (entity.CounterValue, bool) {
Поправил https://github.com/GTech1256/go-yandex-metrics-tpl/pull/7/commits/5f5f39f9193631d70e8ee61ea250c3ed8983bfdf

2023-10-13 00:04 UTC, GTech1256 commented on internal/server/repository/metric/storage.go
> +	return value, ok
Поправил https://github.com/GTech1256/go-yandex-metrics-tpl/pull/7/commits/5f5f39f9193631d70e8ee61ea250c3ed8983bfdf

2023-10-13 00:05 UTC, GTech1256 commented on internal/server/app.go
> +type App interface {
Убрал интерфейс https://github.com/GTech1256/go-yandex-metrics-tpl/pull/7/commits/5f5f39f9193631d70e8ee61ea250c3ed8983bfdf

2023-10-13 01:58 UTC, GTech1256 commented on internal/agent/service/server/service/start_report.go
> +	go func() {
Убрал использование каналов [983dd8e](https://github.com/GTech1256/go-yandex-metrics-tpl/pull/7/commits/983dd8e1c98589955ed1caf0edecebef8c7eb7cc)

2023-10-13 02:00 UTC, GTech1256 commented on cmd/agent/main.go
> +	shutdown := make(chan int)
Я планирую реализовать Graceful Shutdown позже без копипаста и разобраться как это лучше делать.
А временно оставил так

2023-10-13 02:00 UTC, GTech1256 commented on cmd/server/main.go
> +	_, err := server.New(cfg, logger)
Спасибо за ссылки, как написал выше хочу разобраться глубже с Graceful Shutdown и тогда реализовать его

2023-10-16 21:28 UTC, GTech1256 commented on internal/agent/service/server/service.go
> +	Service interface {
Спасибо, понял

Переделал https://github.com/GTech1256/go-yandex-metrics-tpl/pull/7/commits/e9118617af428663cf8b5d6848df09c1db2f6808


Но столкнулся с тем, что duck typing не прям отлично работает в go
Вот пример краткий - https://goplay.space/#8eqMpewu6Vb

В моем коде в `internal/agent/client/server/` подобную конструкицию с server.api.Post() хотел сделать, но из-за отсутсвия duck typing в интерфейсе внутри интерфейса - не получилось так сделать

2023-10-17 07:40 UTC, edylcrm approved these changes

2023-10-18 17:09 UTC, merged